---

- hosts: localhost
  connection: local
#  vars:
#    whoami: "{{ lookup('env', 'USER') }}"
#    user_home: "{{ lookup('env', 'HOME') }}"

  roles:
    - role: basic
    - role: python
    - role: editors_and_environment
#    - role: email_and_internet
    - role: aws
