- name: Install Editors and Environment Packages - APT
  become: yes
  apt:
    name:
      - neovim
      - tmux
      - zsh
    state: present
    autoclean: yes

- name: Install Editors and Environment Packages - SNAP
  become: yes
  snap:
    name:
      - pycharm-community
      - sublime-merge
      - sublime-text
    classic: yes