- name: Install Editors and Environment Packages - APT
  become: yes
  apt:
    name:
      - fonts-powerline
      - neovim
      - powerline
      - python3-neovim
      - tmux
      - zsh
      - zsh-syntax-highlighting
    state: present
    autoclean: yes

#- name: Install Editors and Environment Packages - SNAP - classic
#  become: yes
#  snap:
#    name:
#      - pycharm-community
#      - sublime-merge
#      - sublime-text
#    classic: yes

#- name: Install Editors and Environment Packages - SNAP - strict
#  become: yes
#  snap:
#    name:
#      - drawio
