- name: Install common utility packages
  become: yes
  apt:
    name:
      - htop
      - zip
      - zsh
    state: present
    autoclean: yes

# Install (Bottle) python package.
- name: Install sshmenu
  pip:
    name: sshmenu
    state: present
