- name: Install common utility packages
  become: yes
  apt:
    name:
      - htop
      - keychain
      - python3-pip
      - whois
      - zip
    state: present
    autoclean: yes

# Install (Bottle) python package.
- name: Install sshmenu
  pip:
    name: sshmenu
    state: present
